name: Build and deploy Node.js app to Azure Web App - Crop-Guard

on:
  push:
    branches:
      - Production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build the project (if applicable)
        run: npm run build

      - name: Zip only necessary files for deployment
        run: |
          zip -r release.zip . -x "node_modules/*" ".git/*" ".github/*" ".vscode/*" "*.env" "*.log" "*.zip"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2683E5AE485247028DCC42977538FD47 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0DE028A942094AEC8A6B641092BE6B2C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_91100E7F5DED421EB3AE94EFA8FE609E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Crop-Guard'
          slot-name: 'Production'
          package: .
